name: publish

on:
  push:
    branches: [ main ]

jobs:
  publish-tablerotorneo-api:
    name: "Crear imagen de docker y publicarla en el registry"
    runs-on: ubuntu-latest
    steps:
      - name: Clonar este repository
        uses: actions/checkout@v2
      - name: Login en GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Buildear imagen
        run: docker build . --tag ghcr.io/egnuez/tablerotorneo-api:latest
      - name: Pushear imagen
        run: docker push ghcr.io/egnuez/tablerotorneo-api:latest